//
// File generated by rootcint at Thu Aug  4 15:32:54 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void ktTrackEff_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_ktTrackEff(void *p = 0);
   static void *newArray_ktTrackEff(Long_t size, void *p);
   static void delete_ktTrackEff(void *p);
   static void deleteArray_ktTrackEff(void *p);
   static void destruct_ktTrackEff(void *p);
   static void streamer_ktTrackEff(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::ktTrackEff*)
   {
      ::ktTrackEff *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ktTrackEff >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ktTrackEff", ::ktTrackEff::Class_Version(), "././ktTrackEff.hh", 21,
                  typeid(::ktTrackEff), ::ROOT::DefineBehavior(ptr, ptr),
                  &::ktTrackEff::Dictionary, isa_proxy, 0,
                  sizeof(::ktTrackEff) );
      instance.SetNew(&new_ktTrackEff);
      instance.SetNewArray(&newArray_ktTrackEff);
      instance.SetDelete(&delete_ktTrackEff);
      instance.SetDeleteArray(&deleteArray_ktTrackEff);
      instance.SetDestructor(&destruct_ktTrackEff);
      instance.SetStreamerFunc(&streamer_ktTrackEff);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::ktTrackEff*)
   {
      return GenerateInitInstanceLocal((::ktTrackEff*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ktTrackEff*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr ktTrackEff::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *ktTrackEff::Class_Name()
{
   return "ktTrackEff";
}

//______________________________________________________________________________
const char *ktTrackEff::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::ktTrackEff*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ktTrackEff::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::ktTrackEff*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ktTrackEff::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::ktTrackEff*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ktTrackEff::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::ktTrackEff*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void ktTrackEff::Streamer(TBuffer &R__b)
{
   // Stream an object of class ktTrackEff.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      fName.Streamer(R__b);
      int R__i;
      for (R__i = 0; R__i < 3; R__i++)
         R__b >> effY04[R__i];
      for (R__i = 0; R__i < 3; R__i++)
         R__b >> effY07pteta[R__i];
      for (R__i = 0; R__i < 3; R__i++)
         R__b >> effY07eta[R__i];
      R__b >> effY06;
      R__b >> sysUn;
      R__b.CheckByteCount(R__s, R__c, ktTrackEff::IsA());
   } else {
      R__c = R__b.WriteVersion(ktTrackEff::IsA(), kTRUE);
      TObject::Streamer(R__b);
      fName.Streamer(R__b);
      int R__i;
      for (R__i = 0; R__i < 3; R__i++)
         R__b << effY04[R__i];
      for (R__i = 0; R__i < 3; R__i++)
         R__b << (TObject*)effY07pteta[R__i];
      for (R__i = 0; R__i < 3; R__i++)
         R__b << (TObject*)effY07eta[R__i];
      R__b << effY06;
      R__b << sysUn;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void ktTrackEff::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ktTrackEff.
      TClass *R__cl = ::ktTrackEff::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fName", &fName);
      R__insp.InspectMember(fName, "fName.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*effY04[3]", &effY04);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*effY07pteta[3]", &effY07pteta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*effY07eta[3]", &effY07eta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*effY06", &effY06);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sysUn", &sysUn);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_ktTrackEff(void *p) {
      return  p ? new(p) ::ktTrackEff : new ::ktTrackEff;
   }
   static void *newArray_ktTrackEff(Long_t nElements, void *p) {
      return p ? new(p) ::ktTrackEff[nElements] : new ::ktTrackEff[nElements];
   }
   // Wrapper around operator delete
   static void delete_ktTrackEff(void *p) {
      delete ((::ktTrackEff*)p);
   }
   static void deleteArray_ktTrackEff(void *p) {
      delete [] ((::ktTrackEff*)p);
   }
   static void destruct_ktTrackEff(void *p) {
      typedef ::ktTrackEff current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_ktTrackEff(TBuffer &buf, void *obj) {
      ((::ktTrackEff*)obj)->::ktTrackEff::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::ktTrackEff

/********************************************************
* dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledict();

extern "C" void G__set_cpp_environmentdict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("./ktTrackEff.hh");
  G__cpp_reset_tagtabledict();
}
#include <new>
extern "C" int G__cpp_dllrevdict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ktTrackEff */
static int G__dict_294_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((ktTrackEff*) G__getstructoffset())->GetEffY06());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((ktTrackEff*) G__getstructoffset())->GetEffY04((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ktTrackEff* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ktTrackEff(*((TString*) G__int(libp->para[0])));
     } else {
       p = new((void*) gvp) ktTrackEff(*((TString*) G__int(libp->para[0])));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new ktTrackEff[n];
       } else {
         p = new((void*) gvp) ktTrackEff[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new ktTrackEff;
       } else {
         p = new((void*) gvp) ktTrackEff;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictLN_ktTrackEff));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ktTrackEff*) G__getstructoffset())->SetSysUncertainty((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ktTrackEff*) G__getstructoffset())->PrintInfo();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letdouble(result7, 100, (double) ((ktTrackEff*) G__getstructoffset())->EffAAY07((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Int_t) G__int(libp->para[2])));
      break;
   case 2:
      G__letdouble(result7, 100, (double) ((ktTrackEff*) G__getstructoffset())->EffAAY07((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((ktTrackEff*) G__getstructoffset())->EffAAY07_20((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((ktTrackEff*) G__getstructoffset())->EffPPY06((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letdouble(result7, 100, (double) ((ktTrackEff*) G__getstructoffset())->EffRatio((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Int_t) G__int(libp->para[2])));
      break;
   case 2:
      G__letdouble(result7, 100, (double) ((ktTrackEff*) G__getstructoffset())->EffRatio((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((ktTrackEff*) G__getstructoffset())->EffRatio_20((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((ktTrackEff*) G__getstructoffset())->EffRatio_20_Unc((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ktTrackEff::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ktTrackEff::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ktTrackEff::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ktTrackEff::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ktTrackEff*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ktTrackEff::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ktTrackEff::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ktTrackEff::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dict_294_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ktTrackEff::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dict_294_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ktTrackEff* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ktTrackEff(*(ktTrackEff*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictLN_ktTrackEff));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ktTrackEff G__TktTrackEff;
static int G__dict_294_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ktTrackEff*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ktTrackEff*) (soff+(sizeof(ktTrackEff)*i)))->~G__TktTrackEff();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ktTrackEff*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ktTrackEff*) (soff))->~G__TktTrackEff();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dict_294_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ktTrackEff* dest = (ktTrackEff*) G__getstructoffset();
   *dest = *(ktTrackEff*) libp->para[0].ref;
   const ktTrackEff& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ktTrackEff */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdict {
 public:
  G__Sizep2memfuncdict(): p(&G__Sizep2memfuncdict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdict::*p)();
};

size_t G__get_sizep2memfuncdict()
{
  G__Sizep2memfuncdict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dictLN_ktTrackEff))) {
     ktTrackEff *G__Lderived;
     G__Lderived=(ktTrackEff*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dictLN_ktTrackEff),G__get_linked_tagnum(&G__dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__dictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__dictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ktTrackEff */
static void G__setup_memvarktTrackEff(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dictLN_ktTrackEff));
   { ktTrackEff *p; p=(ktTrackEff*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__dictLN_TString),-1,-1,4,"fName=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TF2),-1,-1,4,"effY04[3]=",0,"Run 4 parameterization");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TH2D),-1,-1,4,"effY07pteta[3]=",0,"Run 7 HT / Run 4 MB pt-eta map, used for pt <= 1.5 GeV/c");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TH1D),-1,-1,4,"effY07eta[3]=",0,"Run 7 HT / Run 4 MB eta map, used for pt > 1.5 GeV/c");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TF2),-1,-1,4,"effY06=",0,"Run 6 parameterization");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"sysUn=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncktTrackEff(void) {
   /* ktTrackEff */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dictLN_ktTrackEff));
   G__memfunc_setup("GetEffY06",752,G__dict_294_0_1, 85, G__get_linked_tagnum(&G__dictLN_TF2), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEffY04",750,G__dict_294_0_2, 85, G__get_linked_tagnum(&G__dictLN_TF2), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - cb", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ktTrackEff",997,G__dict_294_0_3, 105, G__get_linked_tagnum(&G__dictLN_ktTrackEff), -1, 0, 1, 1, 1, 0, "u 'TString' - 0 '\"src/run7eff.root\"' mfName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSysUncertainty",1793,G__dict_294_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - mSys", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintInfo",921,G__dict_294_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EffAAY07",595,G__dict_294_0_6, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"d - 'Double_t' 0 - eta d - 'Double_t' 0 - mPt "
"i - 'Int_t' 0 '0' centBin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EffAAY07_20",788,G__dict_294_0_7, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - eta d - 'Double_t' 0 - mPt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EffPPY06",624,G__dict_294_0_8, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - eta d - 'Double_t' 0 - mPt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EffRatio",784,G__dict_294_0_9, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"d - 'Double_t' 0 - eta d - 'Double_t' 0 - mPt "
"i - 'Int_t' 0 '0' centBin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EffRatio_20",977,G__dict_294_0_10, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - eta d - 'Double_t' 0 - mPt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EffRatio_20_Unc",1366,G__dict_294_0_11, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - eta d - 'Double_t' 0 - mPt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__dict_294_0_12, 85, G__get_linked_tagnum(&G__dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ktTrackEff::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__dict_294_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ktTrackEff::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__dict_294_0_14, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ktTrackEff::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__dict_294_0_15, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ktTrackEff::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__dict_294_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__dict_294_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ktTrackEff::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__dict_294_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ktTrackEff::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__dict_294_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ktTrackEff::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__dict_294_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ktTrackEff::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("ktTrackEff", 997, G__dict_294_0_24, (int) ('i'), G__get_linked_tagnum(&G__dictLN_ktTrackEff), -1, 0, 1, 1, 1, 0, "u 'ktTrackEff' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ktTrackEff", 1123, G__dict_294_0_25, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dict_294_0_26, (int) ('u'), G__get_linked_tagnum(&G__dictLN_ktTrackEff), -1, 1, 1, 1, 1, 0, "u 'ktTrackEff' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__dictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__dictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__dictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__dictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__dictLN_TH2D = { "TH2D" , 99 , -1 };
G__linked_taginfo G__dictLN_TF2 = { "TF2" , 99 , -1 };
G__linked_taginfo G__dictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__dictLN_ktTrackEff = { "ktTrackEff" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledict() {
  G__dictLN_TClass.tagnum = -1 ;
  G__dictLN_TBuffer.tagnum = -1 ;
  G__dictLN_TMemberInspector.tagnum = -1 ;
  G__dictLN_TObject.tagnum = -1 ;
  G__dictLN_TString.tagnum = -1 ;
  G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__dictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__dictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__dictLN_TH1D.tagnum = -1 ;
  G__dictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__dictLN_TH2D.tagnum = -1 ;
  G__dictLN_TF2.tagnum = -1 ;
  G__dictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__dictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__dictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__dictLN_ktTrackEff.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__dictLN_TObject);
   G__get_linked_tagnum_fwd(&G__dictLN_TString);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__dictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__dictLN_TH2D);
   G__get_linked_tagnum_fwd(&G__dictLN_TF2);
   G__get_linked_tagnum_fwd(&G__dictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__dictLN_TMatrixTSparseDiaglEfloatgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__dictLN_ktTrackEff),sizeof(ktTrackEff),-1,29952,(char*)NULL,G__setup_memvarktTrackEff,G__setup_memfuncktTrackEff);
}
extern "C" void G__cpp_setupdict(void) {
  G__check_setup_version(30051515,"G__cpp_setupdict()");
  G__set_cpp_environmentdict();
  G__cpp_setup_tagtabledict();

  G__cpp_setup_inheritancedict();

  G__cpp_setup_typetabledict();

  G__cpp_setup_memvardict();

  G__cpp_setup_memfuncdict();
  G__cpp_setup_globaldict();
  G__cpp_setup_funcdict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdict();
  return;
}
class G__cpp_setup_initdict {
  public:
    G__cpp_setup_initdict() { G__add_setup_func("dict",(G__incsetup)(&G__cpp_setupdict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdict() { G__remove_setup_func("dict"); }
};
G__cpp_setup_initdict G__cpp_setup_initializerdict;

